### ISSUE TITLE
Integration tests failing

### ISSUE THREAD

**Issue by kdmccormick** [regb/scala-smtlib#31] opened 2018-05-24 06:02 UTC
When I run integration tests, I get the following for most of the tests:
```
smtlib.parser.Parser$UnexpectedEOFException: Unexpected end of file. Expected: [OParen]
[info]   at smtlib.parser.ParserCommon$class.check(ParserCommon.scala:90)
```
[Here](https://github.com/regb/scala-smtlib/files/2033981/it-out.txt) is the full output of running `sbt it:test`. All unit tests pass when running `sbt test`.

Specs that might be relevant:
* scala-smtlib commit 3e23701abfdf94648edc2a15880cb74572872234
* sbt version 0.13.7
* openjdk version "1.8.0_131"
* Z3 version 4.5.1
* CVC4 version 1.5
* Debian GNU/Linux 8
* Linux kernel 4.9.0-0.bpo.3-amd64

**Comment by regb** [comment] 2018-06-10 11:45
Hopefully fixed in 91e721481ebc2213991caf1f6c7ae1c055a66251

**Comment by regb** [comment] 2018-10-13 20:05
I downloaded latest CVC4 1.6, and I've done a few tests and it seems that it gets confused when piping the (set-info :source | ...|) over separate lines.

You can get the cvc4 1.6 error with a file info.smt2 containing:

```
(set-option :print-success true)
(set-logic QF_ABV)
(set-info :source |
simple benchmarks.

|)
```

and the command `cat info.smt2 | cvc4 --lang smt`

**Comment by regb** [comment] 2018-10-13 20:06
I'm not sure how to fix that in my library, I would try to ask CVC4 if this is expected behaviour or not, and if not, if they would fix it.

**Comment by regb** [comment] 2018-10-13 20:17
Well, I fixed the tests by removing some empty lines, although that doesn't remove the underlying issue but I will call it closed from my side because I don't think there is much that can be done given the way the interpreter interacts with the underlying solver.

**Closed by regb** 2018-10-13 20:17 UTC
Labels: bug
